### PR TITLE
python 3.7 compatibility

### PR DESCRIPTION
**Pull request by sbrugman**
running on py3.7 (still supported by several projects, requires no change apart from minimum version)

### CODE REVIEW

**Comment by guilatrova** [comment]
Thanks for following the guidelines for commits! 🚀

### Python 3.7 support

Nice catch! Now we support this version, we should ensure our GitHub actions include tests with this version. Do you mind adding this modification?

It's easy, can be added here: https://github.com/guilatrova/tryceratops/blob/main/.github/workflows/ci.yml#L26

### No emojis 😢 

Awww that's sad, do you mind playing/checking this lib [emoji](https://github.com/carpedm20/emoji/) and checking whether it solves the issue? 

I agree it's better to have no emojis than not supporting Windows. So I'm onboard.
If you're busy, I can check later today and append a new commit.

[Reference](https://stackoverflow.com/questions/40446784/display-emoji-in-pythons-console)

**Comment by sbrugman** [comment]
Included python 3.7 to the test matrix.

**Comment by guilatrova** [comment]
@sbrugman To avoid a messy [changelog](https://github.com/guilatrova/tryceratops/blob/main/CHANGELOG.md) may I ask you to squash your last 2 commits?

If unclear I can help with instructions.

**Comment by sbrugman** [comment]
No problem

**Comment by guilatrova** [comment]
Sorry for the confusion @sbrugman I didn't mean to squash ALL commits, just the last two to keep the changelog clean 🙈 

It's a problem because now it won't trigger the auto release...
What we need to do:

- Have at least a `fix:` commit (it will trigger a new release)
- Still have another `ci:` / `chore: ` / `build: ` commit (just to keep things apart, it won't trigger the release)

Does it make sense? I don't want to make it worse for you. Let me know if you're ok doing a rebase, if you need help, or if you wish me to help you! 😁 and once again, thank you for contributing 🙏  I appreciate it a lot!

**Comment by RojerGS** [comment]
(Let me just butt in to say I use Tryceratops on Windows with emojis and it works fine, but I've been using it with Python 3.9.)

**Comment by sbrugman** [comment]
> (@sbrugman, let me just butt in to say I use Tryceratops on Windows with emojis and it works fine, but I've been using it with Python 3.9.)

Each python versions ships with its own version of Unicode. Could be that, or my machine. Need to look into that.

**Comment by guilatrova** [comment]
@sbrugman After running the tests looks like `TypeDict` does not work on Python 3.7.

We might need to do a deeper investigation/refactoring.

See:

```
E   ImportError: cannot import name 'TypedDict' from 'typing' (/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/typing.py)
```

**Comment by guilatrova** [comment]
Due to the lack of activity during this PR I'm closing it.
Happy to reopen if someone has the time to debug and identify what caused the tests to break in Python 3.7.
